### ISSUE TITLE
addon is not buildable using vscode on linux

### ISSUE THREAD

**Issue by codeworkx** [ramack/openhab2-addons#28]
Fixes: https://github.com/codeworkx/ramack-openhab2-addons/commit/f5288c9361acb1ae867bddac1be1161f05151911

**Comment by ramack** [comment]
@codeworkx sorry for ignoring this so long, is this still relevant? I neither catch the problem nor do I think it is mergeable since the version updates :-( Sorry.
Can you check and let me know what to do?

**Comment by ramack** [comment]
closing during the work on OH3 version of the binding in preparation for merging it into upstream. Please reopen if this is still relevant.
