### ISSUE TITLE
use mvn dependency or jar file of resol-vbus-java instead of source code

### ISSUE THREAD

**Issue by ramack** [ramack/openhab2-addons#6]
I asked on
https://community.openhab.org/t/best-practice-for-external-libraries/38218

for best practices on external libs inclusion. Definitly using the source directly is not a good idea, we should adjust it to include a jar, possibly to download it during build via maven?

**Comment by codeworkx** [comment]
https://github.com/codeworkx/ramack-openhab2-addons/commit/f2aaeb002f499bc33603097b02ca834d4c3ca292
